Some more icons and fixes
railwayapp/devicons pull request #13
Opened 2021-09-18 07:42 UTC by Atharv-Pathak-14

Icon added :-
Arch linux
Red hat dark 
Red hat light
Nodejs main logo light 
Node js main logo dark

Fixes :-
Removed the fake java icon and added the legit one 

The colours of the icon which was used before differ from the real logo 

Contact - Atharv Pathak#0001

2021-09-23 06:29 UTC, FarazPatankar requested changes
Thanks for the PR, left some comments for minor changes! :)

2021-09-23 06:29 UTC, FarazPatankar commented on src/icons.ts
> +   i("ArchLinux", { [c]: "arch.svg" }),
Indentation issue on Azure and ArchLinux.

2021-09-23 06:29 UTC, FarazPatankar commented on src/icons.ts
> +  i("NodeJS", { [c]: "nodejs.svg", [d]: "nodejs-black.svg", [l]: "nodejs-white.svg" }),
Can we change the naming to `dark` and `light` instead of `black` and `white` for consistency?

2021-09-23 06:29 UTC, FarazPatankar commented on src/icons.ts
> +   i("RedHat", { [d]: "Red-hat-b.svg", [l]: "Red-hat-w.svg" }),
Same naming suggestion here.

2021-09-23 07:13 UTC, Atharv-Pathak-14 commented
Ok sure you can 👍🏻

2022-01-27 19:16 UTC, Dhananjay-JSR commented
https://github.com/railwayapp/devicons/pull/33 

Made Mentioned Changes and requested PR

2022-01-28 04:04 UTC, Atharv-Pathak-14 commented
I will make a new pr today

2022-01-28 04:04 UTC, closed without merging

2022-01-28 04:11 UTC, Dhananjay-JSR commented
No Need there is already a PR in progress linked with this 


https://github.com/railwayapp/devicons/pull/33